// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/keyang/Workspace/private/vite-learn/comp-tutorial/node_modules/dumi/theme-default/builtins/SourceCode/index.js';
